#!/bin/bash
# Quick guide to deploy to Render

echo "🚀 VoteBlock Render Deployment Guide"
echo "===================================="
echo ""
echo "1. Push your code to GitHub (if not already done):"
echo "   git push origin main"
echo ""
echo "2. Go to https://render.com and sign in"
echo ""
echo "3. Click 'New +' → 'Blueprint'"
echo ""
echo "4. Connect your GitHub account and select this repository"
echo ""
echo "5. Before clicking Deploy, generate a JWT_SECRET:"
echo ""

# Generate a secure JWT secret
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")
echo "   Your JWT_SECRET (save this!):"
echo "   $JWT_SECRET"
echo ""

echo "6. Add the JWT_SECRET to Render as an environment secret:"
echo "   - Go to Environment → Secrets"
echo "   - Click 'Add Secret'"
echo "   - Name: JWT_SECRET"
echo "   - Value: [paste the generated secret above]"
echo ""
echo "7. Click 'Deploy' and wait for both services to build"
echo ""
echo "8. Once deployment is complete:"
echo "   - Get your backend URL from the dashboard"
echo "   - Call this once to initialize the admin user:"
echo "   curl -X POST https://YOUR-BACKEND.onrender.com/api/init"
echo ""
echo "9. Admin credentials (change these after first login!):"
echo "   Email: admin@voteblock.com"
echo "   Password: admin123!"
echo ""
echo "✅ Your app is now live!"
echo ""
echo "📚 For more details, see RENDER_DEPLOYMENT.md"
